### PR TITLE
Add basic dub configuration for a single package name

### PR DESCRIPTION
**Pull request by p0nce**
A simple dub file.
The package name is currently `wg-image`, this can be discussed as needed!

### CODE REVIEW

**Comment by p0nce** [comment]
Other proposals:
- [ ] `imagined`
- [ ] `gwg-image`

**Comment by rikkimax** [comment]
There needs to be a subpackage for test, vs library.
They will need to be split out into separate directories as well.

**Comment by p0nce** [comment]
Yeah what I do usually is put such test programs into an `example/` directory, with another dub.json that depends on the other with a path-based dependency

**Comment by rikkimax** [comment]
These are not examples. They have implementation details scattered throughout with e.g. PNG test suite of images.

**Comment by p0nce** [comment]
so in a `tests/` directory eventually, but those can be `unittest` as well

**Comment by drug007** [comment]
I would prefer `.sdl` format

**Comment by p0nce** [comment]
OK vote here for JSON vs SDLang

**Comment by p0nce** [comment]
Vote here +1 for `wg-image` or -1 or `gwg-image`

**Comment by TurkeyMan** [comment]
Seems votes reflect current state of this PR; merging.

**Comment by p0nce** [comment]
:)

**Pull request merged**
